version: '3.1'

services:
  db:
    image: mongo:4.4
    container_name: tmb_mongodb
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: trackmybudget
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trackmybudget
  tmb:
    build:
      context: "."
      dockerfile: ./compose/prod/Dockerfile
    image: tmb
    restart: unless-stopped
    container_name: tmb_app
    depends_on:
      - db
    volumes:
      - ./files:/data/files:rw
    environment:
      - TMB_BACKEND_DB_URL=mongodb://root:trackmybudget@db:27017
      - TMB_BACKEND_ALLOW_NEW_USERS=True
      - TMB_BACKEND_ROOT_PATH=/api
      - TMB_BACKEND_ORIGIN=http://localhost:8080
      - API_ENTRYPOINT=http://localhost:8080/api/
    ports:
      - "9001:9001"
      - "8080:80"